/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-06-14 08:59:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=viewport content=\"width=device-width, initial-scale=1, user-scalable=0\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/core.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/core2.css\" media=\"only screen and (min-width:800px)\">\r\n");
      out.write("<title>My Social Network</title>\r\n");
      out.write("<style>\r\n");
      out.write(".page-msg {\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: calc(100% - 90px);\r\n");
      out.write("}\r\n");
      out.write(".page-msg .desc {\r\n");
      out.write("\tdisplay: table-cell;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".hide {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write(".feed {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 15px 0;\r\n");
      out.write("\tbox-sizing: border-box;\t\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("}\r\n");
      out.write(".feed .face {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 40px; height: 40px;\r\n");
      out.write("\tborder: 1px solid #ddd;\r\n");
      out.write("\tborder-radius: 40px;\r\n");
      out.write("\tbackground-image: url(\"images/contact.jpg\");\r\n");
      out.write("}\r\n");
      out.write(".feed .name {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("\tline-height: 42px;\r\n");
      out.write("\tfont-size: 1.1em;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".feed .desc {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 15px 0px;\r\n");
      out.write("\tbox-sizing: border-box;\t\r\n");
      out.write("}\r\n");
      out.write(".page-hdr .back {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 10px; top: 16px;\r\n");
      out.write("\twidth: 24px; height: 24px;\r\n");
      out.write("\tbackground-image: url(\"images/btn-back.png\");\r\n");
      out.write("\tbackground-size: 50%;\r\n");
      out.write("\tbackground-position: 50%;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".page-hdr .ctxmnu {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 10px; top: 18px;\r\n");
      out.write("\twidth: 20px; height: 20px;\r\n");
      out.write("\tbackground-size: 20px 20px;\r\n");
      out.write("\tbackground-position: 50%;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write(".page-hdr .ctxmnu.pen {\r\n");
      out.write("\tbackground-image: url(\"images/pen.png\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".page-hdr .navicon {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tleft: 10px; top: 16px;\r\n");
      out.write("\twidth: 24px; height: 24px;\r\n");
      out.write("\tbackground-image: url(\"images/navicon.png\");\r\n");
      out.write("\tbackground-size: 24px 24px;\r\n");
      out.write("\tbackground-position: 50%;\r\n");
      out.write("\tbackground-repeat: no-repeat;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #eee\">\r\n");
      out.write("\t<div class=\"page-hdr\"> MySNS\r\n");
      out.write("\t\t<div class=\"navicon\" onclick=\"showMenu()\"></div>\r\n");
      out.write("\t\t<div class=\"ctxmnu pen\" onclick=\"writeNew()\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"page-mnu\">\r\n");
      out.write("\t\t<div class=\"menu\" onclick=\"onSelect('logout')\">로그아웃</div>\r\n");
      out.write("\t\t<div class=\"menu\" onclick=\"onSelect('close')\">닫기</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"--empty-msg\" class=\"page-msg\">\r\n");
      out.write("\t\t<div class=\"desc\">작성글이 존재하지 않습니다.</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"--feed-list\" class=\"section\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("<script src=\"js/core.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : 'sessioncheck', //내가 보내는 서버주소(컨트롤러)\r\n");
      out.write("\t\tdataType : 'text', //내가 서버로 부터 리턴받는 데이터 형태\r\n");
      out.write("\t\ttype : 'POST', \r\n");
      out.write("\t\tdata : null, //내가 서버로 보내는 데이터\r\n");
      out.write("\t\tsuccess: function (data) { \r\n");
      out.write("\t\t\tif (data == \"OK\") {\r\n");
      out.write("                console.log(\"세션값있음\")\r\n");
      out.write("                start();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (data == \"NO\") {\r\n");
      out.write("\t\t\t\talert(\"로그인이 필요합니다.\");\r\n");
      out.write("\t\t\t\tlocation.replace(\"login\");\r\n");
      out.write("\t\t\t}\t\t\t\r\n");
      out.write("\t      }\r\n");
      out.write("   });\r\n");
      out.write("});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("function start() {\r\n");
      out.write("\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl : \"fetch\", //내가 보내는 서버주소(컨트롤러)\r\n");
      out.write("\t\tdataType : 'text', //내가 서버로 부터 리턴받는 데이터 형태\r\n");
      out.write("\t\ttype : 'POST',\r\n");
      out.write("\t\tdata : null, //내가 서버로 보내는 데이터\r\n");
      out.write("\t\tsuccess: function (data) { \r\n");
      out.write("\t\t\tvar list = JSON.parse(data.trim());\r\n");
      out.write("\t\t\tconsole.log(list);\r\n");
      out.write("\t\t\tconsole.log(list.jsonobj);\r\n");
      out.write("\t\t\tconsole.log(list.id);\r\n");
      out.write("\t\t\t$(\"#--empty-msg\").addClass(\"hide\");\r\n");
      out.write("\t\t\tshowFeeds(list);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showFeeds(list) {\r\n");
      out.write("\tvar str = \"\";\r\n");
      out.write("\tfor (var i=0; i<list.length; i++) {\r\n");
      out.write("\t\tstr += showFeed(list[i]);\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#--feed-list\").html(str);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function showFeed(list) {\r\n");
      out.write("\tvar str = \"<div class='feed mbot-10'>\";\r\n");
      out.write("\t\r\n");
      out.write("\tstr += \"<div class='section phor-16'>\";\r\n");
      out.write("\tstr += \"<div class='face flex-embed'></div>\";\r\n");
      out.write("\tstr += \"<div class='name'>\" + list.id + \"</div>\";\r\n");
      out.write("\tstr += \"<div class='desc'>\" + list.jsonobj + \"</div>\";\r\n");
      out.write("\tstr += \"</div>\";\r\n");
      out.write("\r\n");
      out.write("\treturn str;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showMenu(hide) {\r\n");
      out.write("\tif (hide == false) {\r\n");
      out.write("\t\t$(\".page-mnu\").css(\"left\", \"-240px\");\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\t$(\".page-mnu\").css(\"left\", 0);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function writeNew() {\r\n");
      out.write("\twindow.location.href = \"write\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function onSelect(menu) {\r\n");
      out.write("\tif (menu == \"logout\") {\r\n");
      out.write("\t\tlogout();\r\n");
      out.write("\t}\r\n");
      out.write("\tshowMenu(false);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function logout() {\r\n");
      out.write("\tif(confirm(\"로그아웃 하시겠습니까?\") == true) {\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar sessiondelete = \"sessiondelete\";\r\n");
      out.write("\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"sessioncheck\", //내가 보내는 서버주소(컨트롤러)\r\n");
      out.write("\t\t\tdataType : 'text', //내가 서버로 부터 리턴받는 데이터 형태\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tdata : sessiondelete, //내가 서버로 보내는 데이터\r\n");
      out.write("\t\t\tsuccess: function (data) { \r\n");
      out.write("\t\t\t\tif (data == \"deleteOK\") {\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"login\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t   });\r\n");
      out.write("\t\t\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
